var PAGE_TEMPLATES = {};

PAGE_TEMPLATES.home = `
<section class="snap-section dark-b" id="snap-s0">
<div class="dash-content">
<div class="dash-top"><div><div class="section-label">Live Dashboard</div><div class="dash-title">법무실 진행 현황</div><div class="dash-sub">미처리 문의 및 계약서 검토 요청 실시간 현황</div></div><button class="btn-sm" onclick="loadDashboard()">↻ 새로고침</button></div>
<div class="stat-cards">
<div class="stat-card s-red"><span class="stat-card-label">문의 · 미답변</span><span class="stat-card-right"><span class="stat-card-num" id="sc-inq-pending">—</span><span class="stat-card-unit">건</span></span></div>
<div class="stat-card s-blue"><span class="stat-card-label">문의 · 진행중</span><span class="stat-card-right"><span class="stat-card-num" id="sc-inq-progress">—</span><span class="stat-card-unit">건</span></span></div>
<div class="stat-card s-orange"><span class="stat-card-label">검토 · 대기</span><span class="stat-card-right"><span class="stat-card-num" id="sc-rev-pending">—</span><span class="stat-card-unit">건</span></span></div>
<div class="stat-card s-purple"><span class="stat-card-label">검토 · 진행중</span><span class="stat-card-right"><span class="stat-card-num" id="sc-rev-progress">—</span><span class="stat-card-unit">건</span></span></div>
<div class="stat-card s-green"><span class="stat-card-label">검토 · 합의완료</span><span class="stat-card-right"><span class="stat-card-num" id="sc-rev-agreed">—</span><span class="stat-card-unit">건</span></span></div>
</div>
<div class="dash-tables-grid">
<div class="dash-table-wrap"><div class="dash-table-header"><h4>💬 문의 현황 (미처리)</h4><span id="inq-dash-count">로드 중...</span></div><div class="dash-table-scroll"><table class="ct-table dash-table"><thead><tr><th style="width:150px;">문의자</th><th style="width:180px;">문의유형</th><th>문의제목</th><th style="width:110px;" class="hide-mobile">요청일</th><th style="width:100px;">상태</th><th style="width:130px;" class="hide-mobile">진행자</th></tr></thead><tbody id="dash-inq-tbody"><tr><td colspan="6"><div class="dash-empty">⏳ 로드 중...</div></td></tr></tbody></table></div><div class="dash-pagination" id="inq-pagination" style="display:none;"><button class="pg-btn" id="inq-prev" onclick="changeDashPage('inq',-1)">‹ 이전</button><span class="pg-info" id="inq-pg-info">1 / 1</span><button class="pg-btn" id="inq-next" onclick="changeDashPage('inq',1)">다음 ›</button></div></div>
<div class="dash-table-wrap"><div class="dash-table-header"><h4>📋 계약서 검토 현황 (미처리)</h4><span id="rev-dash-count">로드 중...</span></div><div class="dash-table-scroll"><table class="ct-table dash-table"><thead><tr><th style="width:150px;">요청자</th><th style="width:90px;">당사자</th><th style="width:90px;">계약유형</th><th>계약서명</th><th style="width:110px;" class="hide-mobile">요청일</th><th style="width:100px;">상태</th><th style="width:130px;" class="hide-mobile">진행자</th></tr></thead><tbody id="dash-rev-tbody"><tr><td colspan="7"><div class="dash-empty">⏳ 로드 중...</div></td></tr></tbody></table></div><div class="dash-pagination" id="rev-pagination" style="display:none;"><button class="pg-btn" id="rev-prev" onclick="changeDashPage('rev',-1)">‹ 이전</button><span class="pg-info" id="rev-pg-info">1 / 1</span><button class="pg-btn" id="rev-next" onclick="changeDashPage('rev',1)">다음 ›</button></div></div>
</div>
</div>
<div class="scroll-hint light"><span>Scroll</span><div class="sh-arrow">↓</div></div>
</section>
<section class="snap-section dark" id="snap-s1"><div class="service-inner"><div class="svc-eyebrow">Contract</div><div class="svc-icon-wrap">📝</div><div class="svc-title">계약서 작성 및 검토</div><div class="svc-desc">표준계약서를 자동으로 생성하거나,<br>고객사 양식 계약서를 업로드하여 법무실에 검토를 요청하세요.</div><div class="svc-features"><span class="svc-feature">📄 IGAW · ADP · FIXTYPE 표준계약서 자동 생성</span><span class="svc-feature">🔍 비표준계약서 법무실 검토 요청</span><span class="svc-feature">📬 다운로드 · Slack · 이메일로 계약서 전달</span></div><button class="svc-cta" onclick="showPage('contract')">계약서 작성하기 →</button></div><div class="scroll-hint dark"><span>Scroll</span><div class="sh-arrow">↓</div></div></section>
<section class="snap-section dark-b" id="snap-s2"><div class="service-inner"><div class="svc-eyebrow">Submission</div><div class="svc-icon-wrap">📤</div><div class="svc-title">계약서 원본 제출</div><div class="svc-desc">미제출 계약 목록에서 계약을 선택하면 모든 정보가 자동으로 입력됩니다.<br>PDF 파일을 첨부하고 바로 제출하세요.</div><div class="svc-features"><span class="svc-feature">🔄 계약 현황 리스트 실시간 연동</span><span class="svc-feature">📁 Google Drive 자동 저장</span><span class="svc-feature">✅ 제출 상태 자동 업데이트</span></div><button class="svc-cta" onclick="showPage('submit')">계약서 제출하기 →</button></div><div class="scroll-hint dark"><span>Scroll</span><div class="sh-arrow">↓</div></div></section>
<section class="snap-section dark-p" id="snap-s3"><div class="service-inner"><div class="svc-eyebrow">Inquiry</div><div class="svc-icon-wrap">💬</div><div class="svc-title">법무실 문의하기</div><div class="svc-desc">ERP 등록, 티그리스 품의, 체결된 계약서 확인 등 법무 관련 문의를 남겨주세요.<br>확인 후 Slack 또는 이메일로 답변드립니다.</div><div class="svc-features"><span class="svc-feature">🔍 체결된 계약서 확인 요청</span><span class="svc-feature">✏️ ERP · 티그리스 품의 문의</span><span class="svc-feature">⚖️ 법률 자문 · 기타 문의</span></div><button class="svc-cta" onclick="showPage('inquiry')">문의 접수하기 →</button></div><div class="scroll-hint dark"><span>Scroll</span><div class="sh-arrow">↓</div></div></section>
<section class="snap-section dark-g" id="snap-s4"><div class="service-inner"><div class="svc-eyebrow">Reference</div><div class="svc-icon-wrap">📚</div><div class="svc-title">참고 자료</div><div class="svc-desc">전결규정, 법무 매뉴얼 등 업무에 필요한 참고 자료를 확인하세요.</div><div class="ref-grid"><div class="ref-card" onclick="openRef('approval')" style="cursor:pointer;"><div class="ref-card-icon">📋</div><div class="ref-card-title">전결규정</div></div><div class="ref-card" onclick="openRef('manual')" style="cursor:pointer;"><div class="ref-card-icon">📖</div><div class="ref-card-title">법무 매뉴얼</div></div><div class="ref-card" onclick="openRef('guide')" style="cursor:pointer;"><div class="ref-card-icon">📝</div><div class="ref-card-title">계약서 작성 가이드</div></div></div></div></section>
`;
